version: '3'
services:
  configuration-service:
    image: "ekholabs/configuration-service"
    container_name: "configuration-service"
    ports:
      - "8082:8082"
    links:
      - eureka-service
    depends_on:
      - eureka-service
    networks:
      - elsie-dee-net
  eureka-service:
    image: "ekholabs/eureka-service"
    container_name: "eureka-service"
    ports:
      - "8083:8083"
    networks:
      - elsie-dee-net

networks:
  elsie-dee-net:
    driver: overlay
